# Soldiers of Kolumbo
# A computer role-playing game

require 'app/constants.rb'
require 'app/cheats.rb'
require 'app/extensions.rb'
require 'app/dice.rb'
require 'app/fsm.rb'
require 'app/input.rb'
require 'app/eventbus.rb'
require 'app/rendering.rb'
require 'app/curves.rb'
require 'app/debug.rb'
require 'app/debug_dice.rb'
require 'app/gui.rb'
require 'app/screen.rb'
require 'app/dialogue.rb'
require 'app/names.rb'
require 'app/status_effects.rb'
require 'app/character.rb'
require 'app/portrait.rb'
require 'app/equipment.rb'
require 'app/treasure.rb'
require 'app/mission.rb'
require 'app/company.rb'
require 'app/messagelog.rb'
require 'app/strategy.rb'
require 'app/station_planetview.rb'
require 'app/station_ambience.rb'
require 'app/encounter.rb'
require 'app/adventure.rb'
require 'app/mainmenu.rb'
require 'app/core.rb'
require 'app/notify.rb'
require 'app/sound.rb'
require 'app/music.rb'
require 'app/rules.rb'
require 'app/tick.rb'

# game initialization is in tick.rb
